Phicomm K2&K2P LED Control Update
hanwckf/rt-n56u pull request #495
Opened 2020-11-13 07:33 UTC by JuanLinn

添加了斐讯K2和K2P的灯光控制模式。连接网络时只亮蓝灯，熄灭黄灯。无网络时打开黄灯关闭蓝灯。

2020-11-23 11:36 UTC, hanwckf commented
请使用
```
#if defined (BOARD_K2P) || defined (BOARD_PSG1218)
#endif
```
代替
```
#if ((BOARD_GPIO_LED_POWER == 13 && BOARD_GPIO_LED_WIFI == 14 && BOARD_GPIO_LED_WAN ==15) || (BOARD_GPIO_LED_POWER == 8 && BOARD_GPIO_LED_WIFI == 11 && BOARD_GPIO_LED_WAN ==10))
#endif
```

2020-11-23 11:39 UTC, hanwckf requested changes
请使用
```
#if defined (BOARD_K2P) || defined (BOARD_PSG1218)
#endif
```

2020-11-24 01:27 UTC, JuanLinn commented
已经更改实现方式

2020-11-24 13:30 UTC, hanwckf requested changes
BOARD_K2P, BOARD_PSG1218已经在`board.mk`内定义，不需要在`board.h`里重复定义

2020-11-24 13:36 UTC, Yh793 commented
老哥你这个重新pull requests一次吧，做成一个提交。

2020-11-24 16:27 UTC, JuanLinn commented
> BOARD_K2P, BOARD_PSG1218已经在`board.mk`内定义，不需要在`board.h`里重复定义

好了，非常感谢指导

2020-11-25 01:46 UTC, hanwckf approved these changes

2020-11-25 01:46 UTC, merged